name: Build API Base GHCR Workflow

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: false
        type: string
        default: ${{ github.ref_name == 'staging' && 'latest' || github.ref_name }}
      DOCKER_FILE:
        required: true
        type: string
      TURBO_APP:
        required: true
        type: string
      TURBO_TEAM:
        required: true
        type: string
      PREBUILD_COMMAND:
        required: false
        type: string
    secrets:
      TURBO_TOKEN:
        required: true

env:
  REGISTRY_URL: ghcr.io
  NODE_ENV: ${{ github.ref_name == 'master' && 'production' || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
      NODE_ENV: ${{ github.ref_name == 'master' && 'production' || github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Application Dependencies
        run: npm ci

      - name: Run Prebuild
        if: ${{ inputs.PREBUILD_COMMAND != '' && inputs.PREBUILD_COMMAND != null }}
        run: ${{ inputs.PREBUILD_COMMAND }}

      - name: Lint
        run: npm run lint

      - name: Build Application
        env:
          NODE_ENV: ${{ github.ref_name == 'master' && 'production' || github.ref_name }}
        run: npx turbo run build --filter=${{ inputs.TURBO_APP }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            TURBO_TEAM=${{ inputs.TURBO_TEAM }}
            NODE_ENV=${{ github.ref_name == 'master' && 'production' || github.ref_name }}
          secrets: |
            turbo_token=${{ secrets.TURBO_TOKEN }}
          file: ${{ inputs.DOCKER_FILE }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ github.repository }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}